<template>
    <div class="container relative">
        <div class="my-10 mx-auto max-w-lg text-center">
            <div>
                <nuxt-link to="/" class="inline-block">
                <img src="/img/logo.png" alt="OneClickDB logo" width="50" class="inline" />
                </nuxt-link>
            </div>

            <div class="prose mx-auto max-w-4xl text-center mt-20">      
                <h1 class="">Build In Public. The Tweets.</h1>    
            </div>

            <div class="prose mx-auto max-w-4xl text-center mt-20"><h2><span class="button link-rotate inline-block" @click="friday = !friday">Friday</span></h2></div>
            <div class="mt-4" v-show="friday">
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">I really want to win this. But I struggle a lot with perfectionism and overthinking, and I know I&#39;ll drown in overwhelm if I don&#39;t make a plan.<br><br>So I made a plan. Am I bonkers for completely ignoring design?<a href="https://t.co/nmADNz6fv2">https://t.co/nmADNz6fv2</a> &lt;-- realtime updates<a href="https://twitter.com/hashtag/BuildInPublic?src=hash&amp;ref_src=twsrc%5Etfw">#BuildInPublic</a> <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> <a href="https://t.co/wwAikH3ODg">https://t.co/wwAikH3ODg</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1372956797917569024?ref_src=twsrc%5Etfw">March 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">I&#39;m going with a single-table MySQL table for my backend. Sooooo simple, but I think good enough.<br><br>Am I missing anything here? Is it dumb to store people&#39;s databases as a binary field?<a href="https://twitter.com/hashtag/buildinpublic?src=hash&amp;ref_src=twsrc%5Etfw">#buildinpublic</a> <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> <a href="https://t.co/WoalavB8yj">pic.twitter.com/WoalavB8yj</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1372970189617176576?ref_src=twsrc%5Etfw">March 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">You can now signup, login, reset password, and logout at <a href="https://t.co/JGM7za1DNz">https://t.co/JGM7za1DNz</a><br><br>There&#39;s no point in doing so (because there&#39;s no other functionality). But you can.</p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373008789729767426?ref_src=twsrc%5Etfw">March 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">It works! I think.<br><br>It’s not pretty yet. And all it does is key-value pairs. But it&#39;s a start.<br><br>Wanna help me test?<br><br>I&#39;ll give a free one year membership to the first person to test it out and post a link to your JSON endpoint :)<a href="https://t.co/JGM7za1DNz">https://t.co/JGM7za1DNz</a><a href="https://twitter.com/hashtag/buildinpublic?src=hash&amp;ref_src=twsrc%5Etfw">#buildinpublic</a> <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> <a href="https://t.co/5vfprHgl29">pic.twitter.com/5vfprHgl29</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373037907418570754?ref_src=twsrc%5Etfw">March 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">I would LOVE some feedback on this h1 and h2 🙏❤️<br><br>Too wordy? Too fumbly?<br><br>Also updated the design on <a href="https://t.co/JGM7za1DNz">https://t.co/JGM7za1DNz</a> if anybody wants to give initial thoughts. (still very much a work in progress, though).<a href="https://twitter.com/hashtag/buildinpublic?src=hash&amp;ref_src=twsrc%5Etfw">#buildinpublic</a> <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> <a href="https://t.co/ttvwCxJt0M">pic.twitter.com/ttvwCxJt0M</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373069104169426947?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Yay for version control!!!<br><br>I&#39;m happy enough with the design, and I want to wait on feedback for the copy. So... BONUS TIME.<br><br>But I have no idea yet how it&#39;s going to work. And I&#39;d be way too scared to break things if I couldn&#39;t revert.<br><br>cc <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> (sorry for all the spam) <a href="https://t.co/litQUvGUQc">pic.twitter.com/litQUvGUQc</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373094492509593608?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
            </div>



            <div class="prose mx-auto max-w-4xl text-center mt-20"><h2><span class="button link-rotate inline-block" @click="saturday = !saturday">Saturday</span></h2></div>
            <div class="mt-4" v-show="saturday">
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Hackathon day 2. <a href="https://twitter.com/hashtag/buildinginpublic?src=hash&amp;ref_src=twsrc%5Etfw">#buildinginpublic</a> cc <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> <br><br>If it ain&#39;t broke, don&#39;t fix it?<br><br>Well... I just made a bold product design decision, ditching the suggested interface for a new one.<br><br>Would love feedback.<br><br>I know having two modes might seem complicated, but... (thread) <a href="https://t.co/w4AoN14PMg">pic.twitter.com/w4AoN14PMg</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373292381986902021?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Who likes to have fun?<br><br>I do. And I LOVE &quot;wasting&quot; 15 minutes on frivolous things like this. Because smiles go a long way. <br><br>(watch the last 4 seconds of the video for the giggles)<br><br>Oh, also, Stripe payments are fully functional. NBD.<a href="https://twitter.com/hashtag/hackathon?src=hash&amp;ref_src=twsrc%5Etfw">#hackathon</a> cc <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> <a href="https://t.co/kK8aqVBTO8">pic.twitter.com/kK8aqVBTO8</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373297257018138627?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Trying to find the perfect blend of simplicity and function for the <a href="https://twitter.com/hashtag/hackathon?src=hash&amp;ref_src=twsrc%5Etfw">#hackathon</a>.<br><br>I&#39;m putting a LOT of my eggs in this &quot;Collections&quot; basket, even though it&#39;s worth a max of 35 points.<br><br>Why? Because I think I&#39;ll continue even if I don&#39;t win, and (imo) this is a MANDATORY feature. <a href="https://t.co/Q3ovXxKVQS">pic.twitter.com/Q3ovXxKVQS</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373379566769557504?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">I&#39;m outsourcing my copywriting!<br><br>Want to test your skills? And help me out? And win stuff?<br><br>1. Go to <a href="https://t.co/F8DzSRTPb2">https://t.co/F8DzSRTPb2</a><br>2. Click the &quot;edit me&quot; blob in the bottom right corner.<br>3. Work your magic.<br>4. Send me what you got!<a href="https://twitter.com/hashtag/hackathon?src=hash&amp;ref_src=twsrc%5Etfw">#hackathon</a> cc <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373415371613429763?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Programming can be SO MUCH fun. It can also product SO MUCH anxiety. <br><br>Sometimes the difference is as simple as a more positive outlook.<br><br>This <a href="https://twitter.com/hashtag/hackathon?src=hash&amp;ref_src=twsrc%5Etfw">#hackathon</a> is freaking fun.<br><br>Head to <a href="https://t.co/F8DzSRCeju">https://t.co/F8DzSRCeju</a> to grab an account before I break everything with Collections.</p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373395199892852740?ref_src=twsrc%5Etfw">March 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                
            </div>


            <div class="prose mx-auto max-w-4xl text-center mt-20"><h2><span class="button link-rotate inline-block" @click="sunday = !sunday">Sunday</span></h2></div>
            <div class="mt-4" v-show="sunday">
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">I think it works! Holy crap. This was way harder than I expected (I spent 8 freaking hours on it).<br><br>Going to test a few more times, deploy, and then it&#39;s all copywriting and polishing from here on out! <a href="https://t.co/H7citxi2pd">pic.twitter.com/H7citxi2pd</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373546444687241218?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Looks like everyone is redesigning their OCDB websites. Me too :)<br><br>Once I finally admitted that I was wrong about autosave (whoops <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> ) it freed up enough real estate to have a much cleaner design.<br><br>Thoughts? <a href="https://t.co/L7LulqNzwz">pic.twitter.com/L7LulqNzwz</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373584807377072129?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">It&#39;s 5am, and this hacker is going to bed. Happy, confident, and - for the first time in years - excited about coding. Just needed a little hackathon to shake me up!<br><br>If anybody wants to test out <a href="https://t.co/F8DzSRTPb2">https://t.co/F8DzSRTPb2</a> while I sleep ... I wouldn&#39;t be mad about that.</p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373604211494035456?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Hackathon? Or weekend of friendship?<br><br>- <a href="https://twitter.com/panphora?ref_src=twsrc%5Etfw">@panphora</a> started it off with a generous opp.<br>- <a href="https://twitter.com/kidgdzilla?ref_src=twsrc%5Etfw">@kidgdzilla</a> was first to test, and help me with copy.<br>- <a href="https://twitter.com/brianball?ref_src=twsrc%5Etfw">@brianball</a> has been helping me with ideas.<br>- <a href="https://twitter.com/ayshptk?ref_src=twsrc%5Etfw">@ayshptk</a> and I have been encouraging each other.<br>- So many more!<br><br>Win or lose, it&#39;s a win!</p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373698299581014024?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Welp, we&#39;re live I guess!<a href="https://t.co/V2BdNlGvgX">https://t.co/V2BdNlGvgX</a> site is now powered by OCDB. Woot woot! <a href="https://t.co/5CDxm1O8Ac">https://t.co/5CDxm1O8Ac</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373538791139385346?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Slow Sunday?<br><br>I&#39;ll give 3 months free to anybody who tries <a href="https://t.co/F8DzSRTPb2">https://t.co/F8DzSRTPb2</a> and leaves me a Tweet review within the next 10 hours. The review doesn&#39;t have to be positive (though obv preferable) to qualify.<br><br>And I&#39;ll give 12 months free if you find a bug :)</p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373717258095136769?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Dude. The time and effort and care that went into this. ❤️🤯❤️<a href="https://twitter.com/brianball?ref_src=twsrc%5Etfw">@brianball</a> is a freaking helpful person. <a href="https://t.co/YanfXkTCJc">https://t.co/YanfXkTCJc</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373726392550977537?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Trying not to spread myself too thin.<br><br>OneClickDB has a ton of potential use cases. But I&#39;m tailoring the landing page entirely for developers who want to add dynamic data to static websites.<br><br>I figure it&#39;s best to really drive this message, then can focus on expanding later. <a href="https://t.co/a0F82YYYY8">pic.twitter.com/a0F82YYYY8</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373758826063618050?ref_src=twsrc%5Etfw">March 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet"><p lang="en" dir="ltr">All done.<br><br>About 60 hours ago I started hacking for <a href="https://t.co/wwAikH3ODg">https://t.co/wwAikH3ODg</a><br><br>I learned a lot about myself, had a ton of fun, met great people, and IMO built something awesome.<br><br>Here&#39;s my entry: <a href="https://t.co/F8DzSRTPb2">https://t.co/F8DzSRTPb2</a><br><br>A recap thread. <a href="https://t.co/z39UdFEVqV">pic.twitter.com/z39UdFEVqV</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373808598875136001?ref_src=twsrc%5Etfw">March 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
                <blockquote class="twitter-tweet tw-align-center"  data-conversation="none"><p lang="en" dir="ltr">Oh, and if anybody wants to see how easy OCDB is to use... I made a VueJS example. It&#39;s cake. <a href="https://t.co/aYY58NpFe3">https://t.co/aYY58NpFe3</a></p>&mdash; Pat Griffith (@MrPatGriffith) <a href="https://twitter.com/MrPatGriffith/status/1373828681995448320?ref_src=twsrc%5Etfw">March 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

            </div>
        </div>

    </div>
</template>
<script>
export default {
    data() {
        return {
            friday: false,
            saturday: false,
            sunday: false
        }
    }
}
</script>